### ISSUE TITLE
Unable to see containers

### ISSUE THREAD

**Issue by Ryft917** [tiagorvmartins/portanexus#4]
**Describe the bug**
I'm unable to see any containers or their options (restart etc), but it shows the number of running/exited containers correctly. This is true for both of my Portainer endpoints.

**To Reproduce**
1. Log into the app.
2. No containers are listed, only the number of running and exited containers.

**Expected behavior**
Be able to see and control my containers from the app.

**Screenshots**
![Screenshot_20240910-173339](https://github.com/user-attachments/assets/84b19c38-b26c-43a1-9adf-98f0b417497c)
![Screenshot_20240910-173644](https://github.com/user-attachments/assets/be70b304-1f78-46fc-a11b-a092d27f15aa)

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 2
 - OS: Nothing OS 2.6 (Android 14)
 - App Version 0.1.1

**Additional context**
Access to my Portainer is configured via a Cloudflare tunnel. I've tried setting it up using the local IP address when on the same subnet but it can't find the endpoints at all this way.

**Comment by tiagorvmartins** [comment]
Hey @Ryft917 thank you for testing and providing feedback!

For now the only portainer docker type tested and supported is "1" which matches your endpoint BigBertha endpoint name.

On another note, I have notice during testing that access through http endpoints is blocked when using the installed apk unless some extra allowance is given on the apk manifest, which is not being done now. This means your endpoint url would need to use https, so it would require your access through cloudflare tunnel with https address and valid cert. 

Anyway, it's odd that you can see the running containers but not the stacks, can you confirm that the stacks were created and managed through portainer and are not external stacks?

If you go on your portainer instance can you control those stacks?

I have a setup very similar to yours, but without cloudflare tunnel for this use case, instead using tailscale with caddy pointing to port 9000 of portainer.

Also worth uninstalling to completely clear SecureStore or logging out and adding the details back again, please also confirm you have the apk v0.1.1 from release github page, the link with the icon on README is outdated, need to update it.

Let me know if you eventually sort this out or you need further assistance, would be happy to help!

**Comment by Ryft917** [comment]
Yep, all of my stacks are external (written and controlled directly from my sever), so if your app is looking at stacks rather than the containers themselves then that would explain why none of mine show up. I also only just noticed that you had mentioned stacks specifically with your screenshots!

I just looked at your roadmap and noticed that container management is listed as a v0.2.0 feature, so it sounds like I'll need to wait until that's released. 

Thanks for replying so quickly! I hope the rest of the development goes well :)

**Comment by tiagorvmartins** [comment]
Hey @Ryft917 wanna let you know about some good news, the newest version [v0.1.2 ](https://github.com/tiagorvmartins/portanexus/releases/tag/v0.1.2) supports this now.

You should be able to do both:
- Control the portainer stacks attached to your portainer host url
- But also control the containers on docker linked to that portainer host

As you mentioned this was part of the scope of v0.2.0 with some extra bits, but introducing this part now as requested by you.

Closing the issue for now, if you find any issues with this version let me know on a new issue if possible.
Thank you for the feedback!
