### ISSUE TITLE
Dark mode doesn't persist on app restart

### ISSUE THREAD

**Issue by Ryft917** [tiagorvmartins/portanexus#5]
**Describe the bug**
Restarting the app resets the theme back to light mode.

**To Reproduce**
1. Change the theme to dark mode.
2. Close the app completely (i.e. don't leave it running in the background).
3. Open the app again and it will be in light mode.

**Expected behavior**
The chosen theme should persist on a restart of the app.

**Smartphone (please complete the following information):**
 - Device: Nothing Phone 2
 - OS: Nothing OS 2.6 (Android 14)
 - App Version 0.1.1

**Comment by tiagorvmartins** [comment]
Thank you @Ryft917! 

Yes this is currently not implemented yet, should be something easy to do, will try to include it on next version 👍

**Comment by Ryft917** [comment]
Sounds good! Thanks!

**Comment by tiagorvmartins** [comment]
Hey @Ryft917 just wanna let you know that as part of changes included PR #6 this has been addressed,
Here is the updated apk [v0.1.2](https://github.com/tiagorvmartins/portanexus/pull/6) 

Marking this issue as completed and closed,
Thank you for the feedback!
